# Generated by Django 5.1.2 on 2024-10-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fighters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('blood', models.CharField(max_length=30)),
                ('fighting_style', models.CharField(max_length=30)),
                ('weight_class', models.CharField(max_length=30)),
            ],
        ),
    ]
