# Generated by Django 5.1.2 on 2024-11-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighters',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='fighters_images'),
        ),
        migrations.AlterField(
            model_name='fighters',
            name='blood',
            field=models.CharField(choices=[('A+ve', 'A+ve'), ('A-ve', 'A-ve'), ('B+ve', 'B+ve'), ('B-ve', 'B-ve'), ('O+ve', 'O+ve'), ('O-ve', 'O-ve'), ('AB+ve', 'AB+ve'), ('AB-ve', 'AB-ve')], max_length=30),
        ),
        migrations.AlterField(
            model_name='fighters',
            name='fighting_style',
            field=models.CharField(choices=[('sambo', 'sambo'), ('brazilian jiu jitsu', 'brazilian jiu jitsu'), ('muay thai', 'muay thai'), ('taekwondo', 'taekwondo'), ('boxing', 'boxing'), ('mma', 'mma')], max_length=30),
        ),
        migrations.AlterField(
            model_name='fighters',
            name='weight_class',
            field=models.CharField(choices=[('featherweight', 'featherweight'), ('bantamweight', 'bantamweight'), ('lightweight', 'lightweight'), ('heavyweight', 'heavyweight'), ('flyweight', 'flyweight')], max_length=30),
        ),
    ]
